// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQbeDBbrQ9cXnjYVSVXB7PPMS27EcFTo',
    appId: '1:499844359469:web:50fa0ede51a3b0beca1fa4',
    messagingSenderId: '499844359469',
    projectId: 'mini-social-app-b7263',
    authDomain: 'mini-social-app-b7263.firebaseapp.com',
    storageBucket: 'mini-social-app-b7263.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBut9sDi1FDVpUNzVephKQo7j2qvYITRJA',
    appId: '1:499844359469:android:3f7405aead65aa8bca1fa4',
    messagingSenderId: '499844359469',
    projectId: 'mini-social-app-b7263',
    storageBucket: 'mini-social-app-b7263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqGVYUFFjvggBELgIeeG9uM-uvYkxrCJc',
    appId: '1:499844359469:ios:0dcaeb141cc8cd71ca1fa4',
    messagingSenderId: '499844359469',
    projectId: 'mini-social-app-b7263',
    storageBucket: 'mini-social-app-b7263.appspot.com',
    iosBundleId: 'com.example.flutterMiniSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqGVYUFFjvggBELgIeeG9uM-uvYkxrCJc',
    appId: '1:499844359469:ios:661bacd7ccbd8438ca1fa4',
    messagingSenderId: '499844359469',
    projectId: 'mini-social-app-b7263',
    storageBucket: 'mini-social-app-b7263.appspot.com',
    iosBundleId: 'com.example.flutterMiniSocial.RunnerTests',
  );
}
